"""
Base Strategy - Abstract interface for all trading strategies.
Every strategy MUST inherit from this class.
"""
import asyncio
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any
from enum import Enum
from ..core.logging import get_logger
from ..risk_engine.models import TradeSignal

logger = get_logger(__name__)


class SignalType(str, Enum):
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    CLOSE_LONG = "close_long"
    CLOSE_SHORT = "close_short"


@dataclass
class StrategySignal:
    """Signal generated by a strategy."""
    signal_type: SignalType
    symbol: str
    timeframe: str
    confidence: float  # 0.0 to 1.0
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit_1: Optional[float] = None
    take_profit_2: Optional[float] = None
    take_profit_3: Optional[float] = None
    reason: str = ""
    indicators: Dict[str, Any] = field(default_factory=dict)
    timestamp: Optional[int] = None


@dataclass
class StrategyConfig:
    """Base configuration for all strategies."""
    name: str
    symbols: List[str]
    timeframe: str = "1h"
    risk_per_trade_percent: float = 1.0
    stop_loss_percent: Optional[float] = None
    take_profit_percent: Optional[float] = None
    use_trailing_stop: bool = False
    trailing_stop_percent: Optional[float] = None
    max_open_trades: int = 3
    min_volume_usdt: float = 1_000_000  # Minimum 24h volume
    parameters: Dict[str, Any] = field(default_factory=dict)


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    
    Lifecycle:
    1. on_candle() called when new candle closes
    2. analyze() returns StrategySignal
    3. Signal sent to RiskEngine for validation
    4. If approved, TradeExecutor opens position
    5. on_trade_closed() called when position closes
    """

    def __init__(self, config: StrategyConfig):
        self.config = config
        self._is_running = False
        self._open_signals: Dict[str, StrategySignal] = {}  # symbol -> active signal
        self._candle_buffer: Dict[str, List[Dict]] = {}  # symbol -> recent candles
        self._indicator_cache: Dict[str, Dict] = {}

    @property
    def name(self) -> str:
        return self.config.name

    @property
    def is_running(self) -> bool:
        return self._is_running

    @abstractmethod
    async def analyze(self, symbol: str, candles: List[Dict]) -> StrategySignal:
        """
        Main analysis method.
        Given recent candle data, return a trading signal.
        
        Args:
            symbol: Trading pair
            candles: List of OHLCV dicts, sorted oldest to newest
        
        Returns:
            StrategySignal with signal type and trade parameters
        """
        pass

    @abstractmethod
    def get_required_candles(self) -> int:
        """Return minimum number of candles needed for analysis."""
        pass

    async def on_candle(self, symbol: str, candle: Dict) -> Optional[StrategySignal]:
        """
        Called when a new candle closes.
        Updates buffer and triggers analysis.
        """
        if symbol not in self._candle_buffer:
            self._candle_buffer[symbol] = []

        self._candle_buffer[symbol].append(candle)

        # Keep buffer size manageable
        max_buffer = max(self.get_required_candles() + 50, 200)
        if len(self._candle_buffer[symbol]) > max_buffer:
            self._candle_buffer[symbol] = self._candle_buffer[symbol][-max_buffer:]

        if len(self._candle_buffer[symbol]) < self.get_required_candles():
            return None  # Not enough data yet

        return await self.analyze(symbol, self._candle_buffer[symbol])

    async def on_trade_closed(self, symbol: str, pnl: float, reason: str):
        """Called when a trade is closed. Override for strategy-specific logic."""
        logger.info(f"[{self.name}] Trade closed on {symbol}: PnL={pnl:.2f}, reason={reason}")
        self._open_signals.pop(symbol, None)

    async def start(self):
        """Start the strategy."""
        self._is_running = True
        logger.info(f"Strategy '{self.name}' started for {self.config.symbols}")

    async def stop(self):
        """Stop the strategy."""
        self._is_running = False
        logger.info(f"Strategy '{self.name}' stopped")

    def to_trade_signal(self, signal: StrategySignal, exchange: str) -> Optional[TradeSignal]:
        """Convert a StrategySignal to a TradeSignal for the RiskEngine."""
        if signal.signal_type not in [SignalType.BUY, SignalType.SELL]:
            return None

        direction = "long" if signal.signal_type == SignalType.BUY else "short"

        return TradeSignal(
            symbol=signal.symbol,
            direction=direction,
            exchange=exchange,
            entry_price=signal.entry_price,
            stop_loss=signal.stop_loss,
            take_profit_1=signal.take_profit_1,
            take_profit_2=signal.take_profit_2,
            take_profit_3=signal.take_profit_3,
            risk_percent=self.config.risk_per_trade_percent,
            timeframe=signal.timeframe,
            signal_metadata=signal.indicators,
            use_trailing_stop=self.config.use_trailing_stop,
            trailing_stop_percent=self.config.trailing_stop_percent,
        )

    def get_status(self) -> Dict:
        return {
            "name": self.name,
            "is_running": self._is_running,
            "symbols": self.config.symbols,
            "timeframe": self.config.timeframe,
            "open_signals": len(self._open_signals),
        }
